CREATE TABLE url_redirects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale VARCHAR(35) NOT NULL REFERENCES locales (code) ON DELETE RESTRICT,
    source_path VARCHAR(1000) NOT NULL,
    target_path VARCHAR(1000) NOT NULL,
    status_code SMALLINT NOT NULL DEFAULT 301 CHECK (status_code IN (301, 302, 307, 308)),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_url_redirects_locale_source UNIQUE (locale, source_path)
);

CREATE INDEX idx_url_redirects_locale_target ON url_redirects (locale, target_path);
