CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    object_key VARCHAR(1000) NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    width INTEGER NOT NULL DEFAULT 0,
    height INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'ready', 'failed', 'deleted')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_media_assets_object_key UNIQUE (object_key)
);
CREATE INDEX idx_media_assets_uploader_created ON media_assets (uploader_user_id, created_at DESC);
CREATE INDEX idx_media_assets_status ON media_assets (status);

CREATE TABLE media_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id BIGINT NOT NULL REFERENCES media_assets (id) ON DELETE RESTRICT,
    locale VARCHAR(35) NOT NULL REFERENCES locales (code) ON DELETE RESTRICT,
    alt_text VARCHAR(500) NOT NULL DEFAULT '',
    title VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_media_translations_media_locale UNIQUE (media_id, locale)
);

ALTER TABLE articles ADD COLUMN cover_media_id BIGINT REFERENCES media_assets (id) ON DELETE RESTRICT;
CREATE INDEX idx_articles_cover_media_id ON articles (cover_media_id);
